/* Site data + original copy. Prices are placeholders ($X.XX) until Lorelei sets retail. */

export const site = {
  name: "Calming The Chaos",
  tagline: "EMF Protection and Remediation",
  phone: "(972) 838-7600",
  phoneHref: "tel:+19728387600",
  email: "nevergiveupxx@icloud.com",
  emailHref: "mailto:nevergiveupxx@icloud.com",
  owner: "Lorelei Shafer",
  url: "https://t3kdesigns03.github.io/calmingthechaos",
  logo: "assets/img/logo-lockup.png",
  logoMark: "assets/img/logo-mark.png",
  ogImage: "assets/img/og-banner.png",
};

export const nav = [
  { label: "Shop", href: "shop.html" },
  { label: "How It Works", href: "how-it-works.html" },
  { label: "Start Here", href: "start-here.html" },
  { label: "About", href: "about.html" },
  { label: "FAQ", href: "faq.html" },
  { label: "Contact", href: "contact.html" },
];

/* collections in shopper-first order */
export const collections = [
  { id: "home", num: "01", eyebrow: "Whole home & space", title: "Harmony for the whole building",
    blurb: "Start with the space itself — the field your family lives inside all day and all night." },
  { id: "sleep", num: "02", eyebrow: "Sleep", title: "A quieter field where you rest",
    blurb: "The place you spend a third of your life deserves the calmest environment in the house." },
  { id: "body", num: "03", eyebrow: "On the body", title: "Carry the calm with you",
    blurb: "Hand-finished wearables for the wrist, the pocket, and the bag." },
  { id: "device", num: "04", eyebrow: "On the devices you touch", title: "For the screens in your hands",
    blurb: "The phone, the laptop, the router, the things that are always on — each gets its own chip." },
  { id: "car", num: "05", eyebrow: "In the car", title: "Calm for the commute",
    blurb: "A sealed metal cabin full of electronics is its own environment. Bring harmony along." },
  { id: "upgrade", num: "06", eyebrow: "Upgrades & replacements", title: "Keep your set current",
    blurb: "Fiber-era boosters and gentle replacement parts so your pieces stay their best." },
  { id: "bundle", num: "07", eyebrow: "Starter bundles", title: "Curated to begin well",
    blurb: "Thoughtful starting kits — the pieces that matter most, chosen together." },
];

/* ---------- PRODUCTS ---------- */
export const products = [
  {
    slug: "home-harmonizer", name: "Home Harmonizer", subtitle: "Upgraded for Fiber",
    icon: "box", collection: "home", tag: "Flagship",
    job: "Harmonizes the environmental field of your entire home — from the wiring inside the walls to the wireless weather outside.",
    whoFor: "Any house or building. The foundation piece almost every space begins with.",
    coverage: "About one per 2,500 sq ft.",
    intro: "The Home Harmonizer is the centerpiece of the line — a hand-finished piece designed to bring the whole building into a calmer state. According to EMF Solutions’ approach, it works with both the electrical field moving through your home’s wiring and the outside-in wireless load: cell towers, neighborhood routers, smart meters, and the newer fiber infrastructure reaching more homes each year.",
    place: [
      "Place one near your electrical meter or main panel where it can address the whole structure.",
      "For most homes, one unit covers roughly 2,500 square feet.",
      "Set it and leave it — there is nothing to plug in and nothing to maintain.",
    ],
    challenges: "Larger footprints, metal roofs, rooftop solar, or a cell tower close by can create extra load. In those cases a Booster Box is often added alongside the Home Harmonizer.",
    dims: "Approx. 4 × 4 × 4 in.",
    pairs: ["booster-box", "better-zzzs", "device-chip"],
    seo: "Whole-home EMF harmonizer, upgraded for the fiber era. One per ~2,500 sq ft.",
  },
  {
    slug: "booster-box", name: "Booster Box", subtitle: "For larger or harder spaces",
    icon: "box", collection: "home", tag: "Companion",
    job: "A half-strength companion that adds reach to your Home Harmonizer in bigger or more challenging homes.",
    whoFor: "Homes over ~2,500 sq ft, or with a metal roof, solar array, or a nearby tower.",
    coverage: "Pairs with a Home Harmonizer.",
    intro: "Some homes simply ask for more — extra square footage, a metal roof that reflects and concentrates signal, rooftop solar, or a cell site just down the street. The Booster Box is designed as a half-strength partner to the Home Harmonizer, extending its reach so the whole space stays in the same calm state.",
    place: [
      "Add near the Home Harmonizer, or toward the far end of a larger footprint.",
      "Use when square footage or site conditions call for more than one flagship piece.",
      "Not a standalone — it’s built to work with a Home Harmonizer.",
    ],
    pairs: ["home-harmonizer", "armored-upgrade"],
    seo: "Half-strength Booster Box companion for the Home Harmonizer in larger or harder homes.",
  },
  {
    slug: "room-harmonizer", name: "Room Harmonizer", subtitle: "Upgraded for Fiber",
    icon: "room", collection: "home", tag: "Single space",
    job: "Brings one room into harmony — ideal where you can’t reach a main electrical panel.",
    whoFor: "A bedroom, a rented apartment, a hotel room, a condo, a cubicle, or a dorm.",
    coverage: "One room or zone.",
    intro: "When you can’t access a building’s panel — a hotel for the week, a rental, an office cubicle — the Room Harmonizer brings a single space into a calmer state. It is focused by design and is not equal to a full Home Harmonizer; condos and larger apartments often use several to cover the whole floor plan.",
    place: [
      "Set it in the room where you spend the most time, or where you sleep.",
      "Great for travel — slip it into a bag and set it on the nightstand.",
      "For a full condo or apartment, plan on more than one.",
    ],
    pairs: ["better-zzzs", "cell-chip-ultra", "emf-band"],
    seo: "Single-room EMF harmonizer for bedrooms, rentals, hotels, condos and offices.",
  },
  {
    slug: "better-zzzs", name: "Better ZZZ’s", subtitle: "For the sleep zone",
    icon: "sleep", collection: "sleep", tag: "Sleep",
    job: "A dedicated piece for the bed — placed at the sleep zone to help the space where you rest feel calm.",
    whoFor: "Anyone who wants their bedroom to feel like a true retreat. Many customers reach for this one first.",
    coverage: "One per sleeping area.",
    intro: "We spend about a third of our lives in bed, often surrounded by phones, clocks, and Wi-Fi that never sleeps. Better ZZZ’s is designed for the sleep zone specifically — a quiet, hand-finished piece for the place rest actually happens. Many customers report a calmer, more settled feeling in the bedroom.",
    place: [
      "Position it under the mattress or within the sleep zone, per the enclosed guidance.",
      "One piece per sleeping area.",
      "Pairs naturally with a Room or Home Harmonizer.",
    ],
    warn: "Please note: do not use Better ZZZ’s on a plug-in adjustable bed. Those beds use a Device Chip on the motor instead.",
    pairs: ["room-harmonizer", "device-chip", "home-harmonizer"],
    seo: "Better ZZZ’s — a dedicated EMF harmonizing piece for the sleep zone.",
  },
  {
    slug: "emf-band", name: "EMF Band", subtitle: "Upgraded for Fiber",
    icon: "band", collection: "body", tag: "Wearable",
    job: "A hand-finished band that carries a calmer personal field with you through the day.",
    whoFor: "Everyday wear for adults and kids. The simplest way to bring harmony off the property line and onto the body.",
    coverage: "One per person.",
    intro: "The EMF Band is the piece you wear — to work, to school, on a walk, on a plane. Comfortable enough to forget you have it on, it’s the personal companion to your home pieces. Sized and styled to suit smaller wrists, including children’s.",
    place: [
      "Wear it on the wrist like any band, day or night.",
      "One per person — everyone in the household can have their own.",
      "Step up to the XL for a stronger personal piece.",
    ],
    pairs: ["cell-chip-ultra", "personal-card-ultra", "emf-band-xl"],
    seo: "Wearable EMF Band, upgraded for fiber. Everyday personal harmony for adults and kids.",
  },
  {
    slug: "emf-band-xl", name: "EMF Band XL", subtitle: "Upgraded for Fiber",
    icon: "bandxl", collection: "body", tag: "Stronger",
    job: "The stronger personal band — more presence for those who want the most robust wearable.",
    whoFor: "Adults who want the strongest personal piece, larger wrists, or higher-exposure days.",
    coverage: "One per person.",
    intro: "The XL is the flagship of the wearables — a larger, stronger face for people who want the most robust personal companion, or who spend long days in dense wireless environments. It uses a replaceable face and interchangeable straps, so it can be refreshed and resized over the years.",
    place: [
      "Wear on the wrist; choose silicone or a nylon strap for comfort and fit.",
      "The face and straps are replaceable — see Upgrades & replacements.",
      "One per person; pair with a device chip for the phone you hold most.",
    ],
    pairs: ["xl-band-alternative-nylon-band", "xl-band-face-replacement", "icell-ultra"],
    seo: "EMF Band XL — the strongest wearable, with replaceable face and straps.",
  },
  {
    slug: "personal-card-ultra", name: "Personal Card Ultra", subtitle: "Pocket & bag",
    icon: "card", collection: "body", tag: "Upgraded",
    job: "A slim, upgraded card that tucks into a wallet, pocket, or bag to carry harmony discreetly.",
    whoFor: "Anyone who prefers not to wear a band, or who wants a second personal piece for a purse or backpack.",
    coverage: "One per person or bag.",
    intro: "Not everyone wants something on their wrist. The Personal Card Ultra is the discreet alternative — the size of a credit card, at home in a wallet, a back pocket, or the front pocket of a laptop bag. A quiet way to keep a calmer personal field wherever the day takes you.",
    place: [
      "Slide it into a wallet, pocket, purse, or bag.",
      "Keep one in the bag you carry every day.",
      "Wonderful as a companion to a band, or on its own.",
    ],
    pairs: ["emf-band", "cell-chip-ultra"],
    seo: "Personal Card Ultra — a slim, upgraded EMF card for wallet, pocket, or bag.",
  },
  {
    slug: "cell-chip-ultra", name: "Cell Chip Ultra", subtitle: "For most phones",
    icon: "phone", collection: "device", tag: "Phone",
    job: "The upgraded chip for the phone in your hand all day — for every phone except MagSafe iPhones.",
    whoFor: "Android phones and all iPhones before the iPhone 12. (MagSafe iPhone 12 and later use the iCell Ultra.)",
    coverage: "One per phone.",
    intro: "Your phone is the device you hold closest, longest. The Cell Chip Ultra is the upgraded piece made to sit right on it. It fits virtually every phone — the important exception is the MagSafe iPhone 12 and newer, which have a magnet ring the iCell Ultra is designed for.",
    place: [
      "Apply the chip to the back of the phone or inside the case, per the enclosed steps.",
      "One chip per phone.",
      "iPhone 12 or later? Choose the iCell Ultra instead.",
    ],
    pairs: ["icell-ultra", "emf-band", "personal-card-ultra"],
    seo: "Cell Chip Ultra — upgraded phone chip for all phones except MagSafe iPhone 12+.",
  },
  {
    slug: "icell-ultra", name: "iCell Ultra", subtitle: "For MagSafe iPhones",
    icon: "iphone", collection: "device", tag: "iPhone 12+",
    job: "The chip designed for MagSafe — required for iPhone 12 and later, and works on earlier iPhones too.",
    whoFor: "iPhone 12 and newer (MagSafe). Also compatible with earlier iPhones.",
    coverage: "One per phone.",
    intro: "The iPhone 12 and later added a MagSafe magnet ring that changed how a chip needs to fit. The iCell Ultra is made for exactly that — the required choice for MagSafe iPhones, and fully compatible with older iPhones as well, so it’s the safe pick for any iPhone household.",
    place: [
      "Apply per the enclosed steps, clear of the MagSafe ring so wireless charging still works.",
      "One per phone.",
      "Not sure which iPhone you have? Ask Lorelei and she’ll confirm.",
    ],
    pairs: ["cell-chip-ultra", "laptop-chip-ultra", "emf-band-xl"],
    seo: "iCell Ultra — the MagSafe iPhone chip required for iPhone 12 and later.",
  },
  {
    slug: "laptop-chip-ultra", name: "Laptop Chip Ultra", subtitle: "Two per device",
    icon: "laptop", collection: "device", tag: "Two-pack",
    job: "An upgraded chip set for the laptop, tablet, or desktop you work on — two chips per device.",
    whoFor: "Anyone who spends real hours at a laptop, tablet, or PC — especially with today’s always-connected, AI-era workloads.",
    coverage: "Two chips per computer.",
    intro: "Computers have only gotten busier — always online, always processing. The Laptop Chip Ultra is the upgraded piece for the machine you work on, and it’s applied as two chips per device for full coverage across a larger, harder-working surface.",
    place: [
      "Apply two chips per laptop, tablet, or PC, per the enclosed guide.",
      "One set covers one device.",
      "Add a Device Chip to the router that feeds it.",
    ],
    pairs: ["device-chip", "icell-ultra", "personal-card-ultra"],
    seo: "Laptop Chip Ultra — two upgraded chips per laptop, tablet, or PC.",
  },
  {
    slug: "device-chip", name: "Device Chip", subtitle: "For the always-on things",
    icon: "router", collection: "device", tag: "Versatile",
    job: "The versatile chip for everything else that broadcasts — routers, TVs, speakers, monitors, and more.",
    whoFor: "Routers and Wi-Fi extenders, smart TVs, printers, Alexa/Google speakers, gaming consoles, baby monitors, and plug-in adjustable beds.",
    coverage: "One per device.",
    intro: "Beyond phones and laptops, a modern home hums with connected devices. The Device Chip is the flexible workhorse for all of them — the router the whole house depends on, the smart TV, the speaker on the counter, the baby monitor, the gaming console. It’s also the right piece for a plug-in adjustable bed’s motor.",
    place: [
      "Apply one chip to each device, starting with your main router.",
      "Great for routers, extenders, TVs, printers, smart speakers, consoles, and monitors.",
      "For an adjustable bed, use a Device Chip rather than Better ZZZ’s.",
    ],
    pairs: ["home-harmonizer", "laptop-chip-ultra", "cell-chip-ultra"],
    seo: "Device Chip — for routers, TVs, speakers, consoles, monitors and plug-in beds.",
  },
  {
    slug: "car-harmonizer", name: "Car Harmonizer", subtitle: "12V plug-in",
    icon: "car", collection: "car", tag: "Vehicle",
    job: "Plugs into your 12V outlet to bring a calmer field to the sealed metal cabin you commute in.",
    whoFor: "Any car, truck, or SUV. A must for long commutes and road trips.",
    coverage: "One per vehicle (some hybrids/EVs use two).",
    intro: "A car is a small metal room full of electronics, moving through a changing wireless landscape. The Car Harmonizer plugs into the 12V (cigarette-lighter) outlet and includes a USB pass-through, so you keep a charging port while it works. It brings the same calm approach to the space you commute and travel in.",
    place: [
      "Plug into the 12V outlet; use the built-in USB pass-through to keep charging.",
      "One per vehicle for most cars.",
      "Hybrids and EVs may need two — or a Better ZZZ’s workaround if there’s no second outlet. Ask Lorelei.",
    ],
    pairs: ["cell-chip-ultra", "emf-band", "personal-card-ultra"],
    seo: "Car Harmonizer — 12V plug-in with USB pass-through for cars, hybrids and EVs.",
  },
  {
    slug: "armored-upgrade", name: "Armored Upgrade", subtitle: "Fiber-era booster",
    icon: "armor", collection: "upgrade", tag: "Upgrade",
    job: "An add-on chip that brings older Home Harmonizers up to current, fiber-era strength.",
    whoFor: "Anyone with a Home Harmonizer from before the April 2026 fiber-era update.",
    coverage: "One per 2,500 sq ft.",
    intro: "Infrastructure keeps changing, and the line has kept pace. The Armored Upgrade is an add-on chip that brings earlier Home Harmonizers up to the strength of the current fiber-era units — so a piece you already own can stay current instead of being replaced. Applied at the same one-per-2,500-sq-ft rate as the Home Harmonizer.",
    place: [
      "Add the chip to an existing Home Harmonizer, per the enclosed steps.",
      "One per 2,500 sq ft, matching your Home Harmonizer coverage.",
      "Not needed if your Home Harmonizer is already the fiber-era version.",
    ],
    pairs: ["home-harmonizer", "booster-box"],
    seo: "Armored Upgrade — add-on chip to bring older Home Harmonizers to fiber-era strength.",
  },
  {
    slug: "xl-band-face-replacement", name: "XL Band Face Replacement", subtitle: "Keep your XL current",
    icon: "face", collection: "upgrade", tag: "Replacement",
    job: "A fresh face for your EMF Band XL, so a well-loved band can be renewed rather than replaced.",
    whoFor: "EMF Band XL owners refreshing a worn face or updating to the latest version.",
    coverage: "One face per XL band.",
    intro: "The EMF Band XL is built to last, with a replaceable face at its heart. This is that face — a simple way to renew a band you love, or to bring it up to the current version without buying a whole new piece.",
    place: [
      "Swap the old face for the new one, per the enclosed instructions.",
      "Fits the EMF Band XL.",
      "Pair with a fresh strap for a like-new band.",
    ],
    pairs: ["emf-band-xl", "xl-band-replacement-silicone-band", "xl-band-alternative-nylon-band"],
    seo: "XL Band Face Replacement — a fresh face for the EMF Band XL.",
  },
  {
    slug: "xl-band-alternative-nylon-band", name: "XL Band — Nylon Strap", subtitle: "Alternative band",
    icon: "nylon", collection: "upgrade", tag: "Strap",
    job: "A breathable nylon strap for silicone-sensitive skin or larger wrists.",
    whoFor: "EMF Band XL owners who prefer nylon, have sensitive skin, or need a longer fit.",
    coverage: "One strap.",
    intro: "For anyone sensitive to silicone, or who simply prefers the feel of woven nylon, this alternative strap makes the EMF Band XL comfortable all day. It’s also the answer for larger wrists that need a little more length.",
    place: [
      "Attach to your EMF Band XL face in moments.",
      "A good choice for sensitive skin or larger wrists.",
      "Keep a spare so your band is never out of rotation.",
    ],
    pairs: ["emf-band-xl", "xl-band-face-replacement"],
    seo: "XL Band nylon strap — breathable alternative for sensitive skin or larger wrists.",
  },
  {
    slug: "xl-band-replacement-silicone-band", name: "XL Band — Silicone Strap", subtitle: "Replacement band",
    icon: "silicone", collection: "upgrade", tag: "Strap",
    job: "A fresh silicone strap to keep your EMF Band XL comfortable and looking its best.",
    whoFor: "EMF Band XL owners replacing a worn silicone strap.",
    coverage: "One strap.",
    intro: "The everyday silicone strap, soft and easy to clean. This replacement keeps your EMF Band XL feeling new — a small refresh that makes a well-worn favorite comfortable again.",
    place: [
      "Attach to your EMF Band XL face.",
      "Wipe clean; replace whenever it’s seen enough adventures.",
      "Prefer woven? Try the nylon alternative.",
    ],
    pairs: ["emf-band-xl", "xl-band-alternative-nylon-band"],
    seo: "XL Band silicone strap — replacement band for the EMF Band XL.",
  },
  {
    slug: "home-bundle", name: "Home Bundle", subtitle: "A calm starting kit",
    icon: "bundle", collection: "bundle", tag: "Best start",
    job: "The core trio for a typical home — Home Harmonizer, a Device Chip, and Better ZZZ’s, chosen to work together.",
    whoFor: "A typical single-family home ready to begin with confidence.",
    coverage: "Covers a typical home’s foundation.",
    intro: "If you want one thoughtful place to begin, this is it. The Home Bundle brings together the three pieces most homes start with: the Home Harmonizer for the whole building, a Device Chip for your router, and Better ZZZ’s for the bedroom. It’s the foundation — phones and laptops still get their own chips, and Lorelei can help you round it out.",
    place: [
      "Home Harmonizer at the panel, Device Chip on the router, Better ZZZ’s in the bedroom.",
      "Add phone and laptop chips for the devices you touch most.",
      "Larger home? Ask about adding a Booster Box.",
    ],
    includes: ["home-harmonizer", "device-chip", "better-zzzs"],
    pairs: ["cell-chip-ultra", "laptop-chip-ultra"],
    seo: "Home Bundle — Home Harmonizer + Device Chip + Better ZZZ’s starter kit.",
  },
  {
    slug: "bare-minimum", name: "Bare Minimum", subtitle: "The essentials, thoughtfully",
    icon: "bundle", collection: "bundle", tag: "Essentials",
    job: "A lean starting set — a Room Harmonizer, a phone chip, and a personal piece — for a single room or a first step.",
    whoFor: "Renters, students, travelers, or anyone taking a considered first step.",
    coverage: "One room plus your phone and body.",
    intro: "Not ready for a whole-home setup, or living somewhere you can’t reach the panel? The Bare Minimum covers the three places that matter most for one person: the room you’re in, the phone in your hand, and your own body. It pairs a Room Harmonizer with the right phone chip and a personal piece — a genuinely useful first step.",
    place: [
      "Room Harmonizer where you spend the most time.",
      "Phone chip matched to your device (Cell Chip Ultra or iCell Ultra).",
      "A personal piece — the regular EMF Band or the XL.",
    ],
    includes: ["room-harmonizer", "cell-chip-ultra", "emf-band"],
    pairs: ["personal-card-ultra", "better-zzzs"],
    seo: "Bare Minimum — Room Harmonizer + phone chip + personal band starter set.",
  },
];

export const byId = Object.fromEntries(products.map((p) => [p.slug, p]));

/* rewritten social proof — feelings & environment only, no medical claims */
export const testimonials = [
  { text: "Our bedroom just feels different — calmer, quieter, like the room finally exhales at night. I didn’t expect to notice anything, and I did.", who: "Dana R.", where: "Homeowner, Texas" },
  { text: "Lorelei walked me through exactly what my apartment needed and what it didn’t. No pressure, no upsell — just help. That’s rare.", who: "Marcus T.", where: "Renter, Colorado" },
  { text: "I keep a card in my bag and a band on my wrist. The whole house feels more settled since we added the Home Harmonizer.", who: "Priya N.", where: "Parent of two" },
  { text: "The car one surprised me most. Long drives feel less draining now. My family is fully converted.", who: "Ben & Sara K.", where: "Frequent travelers" },
];

/* FAQ */
export const faqs = [
  { q: "Do these block radiation like a Faraday cage?", a: "No — and that’s an important distinction. According to EMF Solutions, these products are designed to <em>harmonize</em> the environmental field rather than block or shield it. A Faraday cage tries to stop signal (which would also stop your phone from working). These hand-finished pieces are meant to bring the surrounding environment into a calmer state while your devices keep working normally." },
  { q: "What does “harmonize vs. shield” actually mean?", a: "Shielding attempts to physically block electromagnetic signal. Harmonizing, as the manufacturer describes it, uses proprietary natural materials intended to ease the “subatomic chaos” they associate with dense wireless and electrical environments — without blocking the signals your devices rely on. It’s a different philosophy: work <em>with</em> the space rather than wall it off." },
  { q: "What is the “fiber” upgrade about?", a: "As fiber-optic internet and newer infrastructure have rolled out, EMF Solutions updated the line to what they call the fiber-era strength. Newer pieces are marked “Upgraded for Fiber.” If you own an older Home Harmonizer, the Armored Upgrade is an add-on chip meant to bring it up to current strength — one per 2,500 sq ft." },
  { q: "iPhone or Android — which phone chip do I need?", a: "Android phones and any iPhone before the iPhone 12 use the <strong>Cell Chip Ultra</strong>. The iPhone 12 and later (with MagSafe) require the <strong>iCell Ultra</strong>, which also works on older iPhones. If you’re unsure, tell Lorelei your exact model and she’ll confirm." },
  { q: "How many Home Harmonizers does my house need?", a: "The general guidance is about one per 2,500 square feet. Extra challenges — a metal roof, rooftop solar, a nearby cell tower, or a large footprint — can call for a Booster Box alongside the Home Harmonizer. Lorelei is happy to help you size it for your specific home." },
  { q: "I have a metal roof / solar. Does that change things?", a: "It can. Metal roofs and solar arrays can concentrate or reflect signal, adding to the load on a space. Many homes in that situation add a Booster Box to the Home Harmonizer. Share your details and we’ll suggest a sensible setup." },
  { q: "Are the bands safe for kids?", a: "Yes — the EMF Band is sized and styled with smaller wrists in mind, and many families put one on every member of the household. As always, these are general-wellness pieces, not medical devices." },
  { q: "I have an adjustable (plug-in) bed. What do I use?", a: "Use a <strong>Device Chip</strong> on the bed’s motor rather than Better ZZZ’s. Better ZZZ’s is designed for a standard sleep zone; a powered adjustable bed is treated like any other plug-in device." },
  { q: "What about hybrids and EVs?", a: "The Car Harmonizer plugs into a 12V outlet with a USB pass-through. Hybrids and electric vehicles sometimes benefit from two units, or a Better ZZZ’s workaround where there isn’t a second outlet. Ask Lorelei about your vehicle." },
  { q: "How long until I notice a difference?", a: "It varies from person to person and home to home. Many customers report a calmer feeling, easier sleep, or a more settled space over the first days and weeks — but these are personal experiences, not guarantees, and nothing here is intended to treat any condition." },
];

export const disclaimerFull =
  "These products are intended for general wellness and environmental harmony only. They are not medical devices and are not intended to diagnose, treat, cure, or prevent any disease or health condition. They are not FDA approved or evaluated, and no medical outcome is claimed or implied. References to laboratory work, blood microscopy, thermal imaging, mold observations, and practitioner testing describe testing reported by the manufacturer, EMF Solutions; results have not been independently verified by Calming The Chaos and individual experiences vary. Products in this line were originally developed by EMF Solutions and are retailed by Calming The Chaos. Customer comments describe personal impressions of comfort, sleep, and the feeling of a space, not medical results.";

export const disclaimerShort =
  "For general wellness and environmental harmony. Not a medical device; not intended to diagnose, treat, cure, or prevent any disease. Originally developed by EMF Solutions; retailed by Calming The Chaos.";
